config/routes.rb
Rails.application.routes.draw do

  match "/calci/calculator"=> "calci#calculator", via: [:post,:get]
  match "/nimisha"=> "welcome#nimisha", via: [:post], as: :nimisha
  get "/welcome/get_comments"
  get "/welcome/comments_body"
  root 'welcome#index'
  resources :posts do
    resources :comments
  end
  resources :calci

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates :body , presence:true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :email,presence:true
	validates :title,presence:true
	validates :body,presence:true
	has_many :comments
	mount_uploader :image, ImageUploader
	mount_uploader :attachment, AttachmentUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calci_controller.rb
class CalciController < ApplicationController

	def new
		if params[:number1] or params[:number2]
			@num1=params[:number1].to_i
			@num2=params[:number2].to_i
			@sum=@num1+@num2
			@sub=@num1-@num2
			@multi=@num1*@num2
			@divi=(@num1/@num2).to_f
			@avg=((@num1+@num2)/2).to_f
		end
	end


	def calculator
		if params[:number1] or params[:number2]
			@num1=params[:number1].to_i
			@num2=params[:number2].to_i
			@sum=@num1+@num2
			@sub=@num1-@num2
			@multi=@num1*@num2
			@divi=(@num1/@num2).to_f
			@avg=((@num1+@num2)/2).to_f
		end
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		
		body= params[:comment][:body]
		@post=Post.find_by(id:params[:post_id])
		@comment=@post.comments.new(body:body)
		respond_to do |format|
			if @comment.save
				format.html do
					flash[:notice]="successfully commented"
					if params[:comment][:from_page]=="index"
						PostMailer.notify_user_on_comment(@post.email).deliver
						redirect_to posts_path
					elsif params[:comment][:from_page]=="show"
						PostMailer.notify_user_on_comment(@post.email).deliver
						redirect_to post_path(@post)
					end
				end
				format.js do
					if params[:comment][:from_page]=="index"
						PostMailer.notify_user_on_comment(@post.email).deliver
						
					elsif params[:comment][:from_page]=="show"
						PostMailer.notify_user_on_comment(@post.email).deliver
					end

				end

			else
				format.html do 
					flash[:danger]=@comment.errors.full_messages.join(",")
					if params[:comment][:from_page]=="index"
						redirect_to posts_path
					elsif params[:comment][:from_page]=="show"
						redirect_to post_path(@post)
					end

				end
				format.js {render js: 'true'}
			end	
		end
	end

	def show
		@post=Post.find_by(id:params[:post_id])
		@comment=@post.comments.find_by(id:params[:id]) if @post.present?
		if @comment
			flash.now[:info]="you can see your comment here.."
		else
			flash[:danger]="comment not found...."
			redirect_to posts_path
		end
	end

	def edit
		@post=Post.find_by(id: params[:post_id])
		@comment=@post.comments.find_by(id:params[:id]) if @post.present?

		if @comment
			flash.now[:info]="you can edit your comment here.."
		else
			flash[:danger]=@comment.errors.full_messages.join(",")
			redirect_to posts_path
		end
	end

	def destroy
		@post=Post.find_by(id: params[:post_id])
		@comment=@post.comments.find_by(id:params[:id]) if @post.present?

		if @comment.destroy
			flash[:notice]="your comment has been successfully deleted.."
			redirect_to posts_path
		else
			flash[:danger]=@comment.errors.full_messages.join(",")
			redirect_to posts_path
		end
	end

	def update
		@post=Post.find_by(id: params[:post_id])
		@comment=@post.comments.find_by(id:params[:id]) if @post.present?
		if @comment.update_attributes(body:params[:comment][:body])
			flash[:notice]="your comment has been updated.."
			redirect_to posts_path
		else
			flash[:danger]=@comment.errors.full_messages.join(",")
			redirect_to posts_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post=Post.new
		if flash.empty?
			flash.now[:info]="Here you can create new posts"
		end
	end

	def create
		email=params[:post][:email]
		title=params[:post][:title]
		body=params[:post][:body]
		image=params[:post][:image]
		attachment=params[:post][:attachment]
		if params[:post][:image].present?
			image=params[:post][:image]
		else
			image="default.png"
		end
		@post=Post.new(email:email, title:title, body:body, image:image, attachment:attachment)
		if @post.save
			flash[:notice]="Post has been successfully created!"
			puts "created"
			PostMailer.notify_user(email).deliver
			redirect_to posts_path
		else
			flash[:danger]=@post.errors.full_messages.join(",")
			redirect_to posts_path
		end         
	end

	def index
		@post=Post.new
		@posts=Post.all.order('created_at DESC')
		# @comment=@post.comments.new
		# @comments=@post.comments.all
	end

	def show
		@post=Post.find_by(id:params[:id])
		@comment=@post.comments.new if @post.present?
		if @post
			# hflash.now[:info]="you can see your post here.."
		else
			redirect_to posts_path
		end
	end

	def destroy
		@post=Post.find_by(id: params[:id])
		if @post.destroy
			flash[:notice]="your post has been successfully deleted.."
			redirect_to posts_path
		else
			flash[:danger]=@post.errors.full_messages.join(",")
			redirect_to posts_path
		end
	end

	def edit
		@post=Post.find_by(id: params[:id])

		if @post
			flash.now[:info]="you can edit your post here.."
		else
			flash[:danger]=@post.errors.full_messages.join(",")
			redirect_to posts_path
		end
	end

	def update
		@post=Post.find_by(id: params[:id])
		if @post.update_attributes(email:params[:post][:email], title:params[:post][:title] , body:params[:post][:body], image:params[:post][:image], attachment:params[:post][:attachment])
			flash[:notice]="your post has been updated.."
			PostMailer.notify_user_on_update(params[:post][:email]).deliver
			redirect_to posts_path
		else

			flash[:danger]=@post.errors.full_messages.join(",")
			redirect_to posts_path
			
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@text="Hello User....!!!!!!"
	end

	def nimisha
	end

	def get_comments
		@post=Post.find_by(id:params[:post_id])
		@comments=@post.comments.pluck(:id)
		puts @comments
		respond_to do |format|
			format.html
		
			format.json{render :json => @comments}
		end
	end


	def comments_body
		body=Array.new
		@post=Post.find_by(id:params[:post_id])
		# @post_body=@post.body
		# body << @post_body
		# raise @post_body.to_yaml
		@comments=@post.comments.pluck(:body)
		respond_to do |format|
			format.html
			format.json{render :json => @comments}
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calci_helper.rb
module CalciHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calci/calculator.html.erb
<h1 class="text-center font" > The result is :</h1>
<br>
The addition of <%=@num1%> and <%=@num2%> is:      <%=@sum%> 
<br>
The subraction of <%=@num1%> and <%=@num2%> is:    <%=@sub%>
<br>
The multiplication of  <%=@num1%> and <%=@num2%> is:      <%=@multi%>
<br>
The division of <%=@num1%> and <%=@num2%> is:       <%=@divi%>
<br>
The average of <%=@num1%> and <%=@num2%> is:           <%=@avg%>

app/views/calci/new.html.erb
<div class="top-margin">
	<h1 class="text-center">CALCULATOR</h1>
	<%=form_tag new_calci_path, method: :GET,class: "form-horizontal"  do %>
		<div class="form-group">
			<%=label_tag :number1,"Number-1 :", class: "col-md-2 control-label" %>
			<div class="col-md-10">
				<%=text_field_tag :number1,"", class: "form-control", placeholder: "Enter first number"%>
			</div>	
		</div>
		<div class="form-group">
			<%=label_tag :number2,"Number-2:", class: "col-md-2 control-label"%>
			<div class="col-md-10">
				<%=text_field_tag :number2, "", class: "form-control", placeholder: "Enter second number"%>
			</div>
		</div>
		<div class="col-sm-offset-2 col-sm-10">
			<%=submit_tag "RESULT", class: "btn btn-success"%>
		</div>
	<%end%>
</div>
<%if @sum %>
	<h1 class="text-center font" > The result is :</h1>
	<br>
	The addition of <%=@num1%> and <%=@num2%> is:      <%=@sum%> 
	<br>
	The subraction of <%=@num1%> and <%=@num2%> is:    <%=@sub%>
	<br>
	The multiplication of  <%=@num1%> and <%=@num2%> is:      <%=@multi%>
	<br>
	The division of <%=@num1%> and <%=@num2%> is:       <%=@divi%>
	<br>
	The average of <%=@num1%> and <%=@num2%> is:           <%=@avg%>
<%end%>
<br>
<%= link_to "BACK", :back%>

app/views/comments/create.js.erb
$('.comment-sector<%=@post.id%>').prepend('<%=@comment.body%>');

app/views/comments/edit.html.erb
<h1 class="text-center">EDIT COMMENT FORM</h1>
Comment:
		<br>
		<br>
		<%=form_for [@post,@comment], html:{class: "form-horizontal"} do |f|%>
			<div class="form-group">
				<div class="col-md-10">			
					<%=f.text_area :body, class: "form-control"%>
					
				</div>

		 		<div class=" col-sm-2">
					<%=f.submit "UPDATE COMMENT", class: "btn btn-success"%>
				</div>
		 	</div>
		<%end%>
		<%= link_to "BACK", :back%>

app/views/comments/show.html.erb
<h1> Comment is:</h1>
COMMENT: <%=@comment.body%>
<br>
<i><%=time_ago_in_words(@comment.created_at)%> ago</i>
<br>
<%= link_to "BACK", :back%>

app/views/layouts/_flash.html.erb
<div class="col-md-3 col-md-offset-9" id="flash">
    <% flash.each do |name,msg| %>
        <% if "#{name}" == "alert"%>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= msg %>
            </div>
        <% elsif "#{name}" == "notice" %>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= msg %>
            </div>
        <% else %>
            <div class="alert alert-<%= name %>">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= msg %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
	  <div class="container">
	    <h6>this is a footer </h6>
	  </div>
	</nav>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "POST-APP", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><%=link_to "Create Post", new_post_path%> <span class="sr-only">(current)</span></li> -->
        <li><%=link_to "Create Post", posts_path%></li>
        <li><%=link_to "Use Calculator", new_calci_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostApp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- this will show partial -->
<%=render 'layouts/header'%>
<div class="container">
	<%=render 'layouts/flash'%>
	<%= yield %>
</div>
<!-- this will show partial -->
<%=render 'layouts/footer'%>
</body>
</html>

app/views/posts/abc.js.erb
alert("hello prateek");

app/views/posts/edit.html.erb
<div class="top-margin">
	<h1 class="text-center">EDIT POST FORM</h1>
	<%=form_for @post, html:{class: "form-horizontal"} do |f|%>
		<%if @post.image.present?%>
			<%=image_tag @post.image.large_thumb.url%>
			<br>
		<%else%>
			<%= image_tag "default.png", width:"1100", height: "249"%>
			<br>
		<%end%>
			<br>
			<%=f.file_field :image%>
			<br>
		<%if @post.attachment.present?%>	
			Attachment: <%= link_to @post.attachment.identifier, @post.attachment.url%>
		<%else%>
			<%="No Attachment"%>
		<%end%>
			<%=f.file_field :attachment%>
			<br>
		<div class="form-group">
			<%=f.label :email, class: "col-md-1"%>
			<div class="col-md-11">
				<%=f.text_field :email, class: "form-control"%>
			</div>
		</div>
		<div class="form-group">
			<%=f.label :title, class: "col-md-1"%>
			<div class="col-md-11">
				<%=f.text_field :title, class: "form-control"%>
			</div>
		</div>
		<div class="form-group">
			<%=f.label :body, class: "col-md-1"%>
			<div class="col-md-11">
				<%=f.text_area :body, class: "form-control"%>
			</div>
		</div>
		<div class="col-sm-offset-1 col-sm-11">
			<%=f.submit "UPDATE POST", class: "btn btn-success"%>
		</div>
	<%end%>
<br>
<%= link_to "BACK", :back%>

app/views/posts/index.html.erb
<div class="top-margin">
	<h1 class="text-center"><u>CREATE NEW POST</u></h1>
	<div class="col-md-12">
		<%=form_for @post, html:{class: "form-horizontal", multipart: true} do |f|%>
			<div class="form-group">
				<%=f.label :email, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_field :email, class: "form-control", placeholder: "Enter your Email"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :title, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_field :title, class: "form-control", placeholder: "Enter post title"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :body, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_area :body, class: "form-control", placeholder: "Enter post body"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :image, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.file_field :image%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :attachment, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.file_field :attachment%>
				</div>
			</div>
			<div class="col-sm-offset-1 col-sm-11">
				<%=f.submit "Create New Post", class: "btn btn-success"%>
			</div>
		<%end%>
	</div>
	<br>
	<br>

	<h1 class="text-center"><i>All the  created posts are........</i></h1>
	<%@posts.each do |post|%>
		<div class="col-md-12">
			<%if post.image.present?%>
				<%= image_tag post.image.thumb.url%>
			<%else%>
				<%= image_tag "default.png", width:"100", height: "100"%>
			<%end%>
		</div>
		<br>
		<div class="col-md-12">
			Attachment:
			<%if post.attachment.present?%>
			 	<%= link_to post.attachment_identifier, post.attachment.url%>
			<%else%>
			 	<%="No Attachment"%>
			<%end%>
			<br>
			EMAIL: <%=post.email%>
			<br>
			TITLE: <%= post.title%>
			<br>
			BODY: <%= post.body%>
			<br>
			<i><%=time_ago_in_words(post.created_at)%> ago</i>
			<br>
				<%=link_to "SHOW POST",post_path(post.id), class: "btn btn-primary btn-xs"%>
			  	<%=link_to "EDIT POST",edit_post_path(post.id), class: "btn btn-info btn-xs"%>
			  	<%= link_to "DELETE POST", post_path(post.id), method: :DELETE, data: {confirm:"Are you sure you want to DELETE it???"}, class: "btn btn-default btn-xs"%>
			 <br>
		</div>
		<div class="col-md-12">
			 Comment:

			<%=form_for [post,post.comments.new], html:{class: "form-horizontal"}, remote:true do |f|%>
				<div class="form-group">
					<div class="col-md-10">			
						<%=f.text_area :body, class: "form-control", placeholder: "Type your comment"%>
						<%=f.hidden_field :from_page, value:"index"%>
					</div>

			 		<%=f.submit "Comment", class: "btn btn-success col-md-2"%>
			 	</div>
			<%end%>
			<% if post.comments.count>0 %>
				<div class="comment-sector<%=post.id%>">
					<%post.comments.where.not(body:nil).order('created_at DESC').each do |comment|%>
				 		<div class= "col-md-6"> <%=comment.body%></div>
				 		 <div class= "col-md-6">
				 		 	<%=link_to "SHOW COMMENT",post_comment_path(post.id,comment.id), class: "btn btn-primary btn-xs"%>
				 		 	<%=link_to "EDIT COMMENT",edit_post_comment_path(post.id,comment.id), class: "btn btn-info btn-xs"%>
				  			<%= link_to "DELETE COMMENT", post_comment_path(post.id,comment.id), method: :DELETE, data: {confirm:"Are you sure you want to DELETE it???"}, class: "btn btn-default btn-xs"%>	
				  		</div>

				 		 <br>
				 		 <div class= "col-md-6">
				 		 <i><%=time_ago_in_words(comment.created_at)%> ago</i>
				 		 </div>
				 		 <hr>	 	
					<%end%>
				</div>
			<%end%>

			<hr>
		
		</div>
	<%end%>

	<table class="table table-hover table-responsive">
	  	<thead>
		  	<tr>
		  		<th>EMAIL</th><th> TITLE</th><th>BODY</th><th>CREATED AT</th><th class='text-center'>ACTIONS</th>
		  	</tr>
	  	</thead>
	  	<tbody>
		  	<%@posts.each do |post|%>
			  	<tr>
			  		<td><%=post.email%></td>
			  		<td> <%= post.title%></td>
			  		<td> <%= post.body%></td>
			  		<td><i><%=time_ago_in_words(post.created_at)%> ago</i></td>
			  		<td><%=link_to "SHOW POST",post_path(post.id), class: "btn btn-primary btn-xs"%>
				  	<%=link_to "EDIT POST",edit_post_path(post.id), class: "btn btn-info btn-xs"%>
				  	<%= link_to "DELETE POST", post_path(post.id), method: :DELETE, data: {confirm:"Are you sure you want to DELETE it???"}, class: "btn btn-default btn-xs"%></td>

			  	</tr>
			<%end%>
		</tbody>
	</table>
	<%=link_to "BACK",:back%>
</div>

app/views/posts/new.html.erb
<div >
<div class="top-margin">
	<h1 class="text-center"><u>CREATE NEW POST</u></h1>
	<div class="col-md-12">
		<%=form_for @post, html:{class: "form-horizontal", multipart: true} do |f|%>
			<div class="form-group">
				<%=f.label :email, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_field :email, class: "form-control", placeholder: "Enter your Email"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :title, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_field :title, class: "form-control", placeholder: "Enter post title"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :body, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.text_area :body, class: "form-control", placeholder: "Enter post body"%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :image, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.file_field :image%>
				</div>
			</div>
			<div class="form-group">
				<%=f.label :attachment, class: "col-md-1"%>
				<div class="col-md-11">
					<%=f.file_field :attachment%>
				</div>
			</div>
			<div class="col-sm-offset-1 col-sm-11">
				<%=f.submit "Create New Post", class: "btn btn-success"%>
			</div>
		<%end%>
	</div>

app/views/posts/show.html.erb
<h1 class="text-center"> Your created post is:</h1>
<%if @post.image.present?%>
	<%=image_tag @post.image.large_thumb.url%>
<%else%>
	<%= image_tag "default.png", width:"1100", height: "249"%>
<%end%>
<br>
<%if @post.attachment.present?%>
	Attachment: <%= link_to @post.attachment_identifier, @post.attachment.url%>
<%else%>
	Attachment: <%="No Attachment"%>
<%end%>
<br>
EMAIL: <%=@post.email%>
<br>
TITLE: <%=@post.title%>
<br>
BODY: <%= @post.body%>
<br>
CREATED AT: <%=time_ago_in_words(@post.created_at)%> ago
<br>
UPDATED AT: <%=time_ago_in_words(@post.updated_at)%> ago
<br>
Comment:
<br>
		<%=form_for [@post,@comment], html:{class: "form-horizontal"} do |f|%>
			<div class="form-group">
				<div class="col-md-10">			
					<%=f.text_area :body, class: "form-control", placeholder: "Type your comment"%>
					<%=f.hidden_field :from_page, value:"show"%>
				</div>

		 		<%=f.submit "Comment", class: "btn btn-success col-md-2"%>
		 	</div>
		<%end%>
				<br>
		<% if @post.comments.count >0 %>
			<%@post.comments.where.not(body:nil).order('created_at DESC').each do |comment|%>
		 		<%=comment.body%>
		 		<br>
		    	<i><%=time_ago_in_words(comment.created_at)%> ago</i>
			 	<hr>			 	
			<%end%>
		<%end%>
<%= link_to "BACK", :back%>

app/views/welcome/abc.js.erb
$('#comments').empty();
<%@comments.each do |comment|%>
	$('#comments').append("<option><%=comment%></option>");
<%end%>

app/views/welcome/get_comments.js.erb
alert("hello");

app/views/welcome/index.html.erb
<!-- <div class="row">
	<div class="col-md-12">
		<div class="text-center"><u><h1><%=@text%></h1></u></div>
	</div>
</div>
<%=link_to "Create new Post",new_post_path, class: "btn btn-sm btn-primary"%>
<%=link_to "View all Post",posts_path, class: "btn btn-sm btn-info"%>
<%= link_to "Use Calculator", new_calci_path, class: "btn btn-sm btn-default"%>
<%=button_tag "RESULT1", class: "btn btn-success", id: "result1"%>
<%=button_tag "RESULT2", id: "result2"%>
<%=button_tag "RESULT3", id: "result3"%> -->

<div class="welcome_page">
	<div class="top_margin">
		<h1 class="text-center">FORM</h1>
		<div class="row">
			<div class='col-md-6'>
				<%=form_tag nimisha_path, method: :POST,class: "form-horizontal"  do %>
					<div class="form-group">
						<%=label_tag :username,"Username :", class: "col-md-4 control-label custom_label" %>
						<div class="col-md-8">
							<%=text_field_tag :username,"", class: "custom_text", placeholder: "Enter username"%>
						</div>	
					</div>
					<div class="form-group">
						<%=label_tag :email,"Email:", class: "col-md-4 control-label custom_label"%>
						<div class="col-md-8">
							<%=text_field_tag :email, "", class: "custom_text", placeholder: "Enter email"%>
						</div>
					</div>
					<div class="form-group">
						<%=label_tag :password,"Password:", class: "col-md-4 control-label custom_label"%>
						<div class="col-md-8">
							<%=text_field_tag :password, "", class: "custom_text", placeholder: "Enter password"%>
						</div>
					</div>
					<div class="form-group">
						<%=label_tag :confirm_password,"Confirm Password:", class: "col-md-4 control-label custom_label"%>
						<div class="col-md-8">
							<%=text_field_tag :confirm_password, "", class: "custom_text", placeholder: "Confirm Password"%>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-4 col-md-offset-1">
							<%=select_tag "actions", options_for_select(["yes","no"]),class: "form-control", prompt: "--Select--"%>
						</div>
						<div class="col-md-7">
							<%=submit_tag "SUBMIT", class: "custom_submit"%>
						</div>
					</div>	
				<%end%>
			</div>	
			<div class='col-md-6'>
				<div class="col-md-5 col-md-offset-1">
					Post<%=select_tag "posts", options_for_select(Post.pluck(:id)),class: "form-control", prompt: "-Select Post-"%>
				</div>
				<div class="col-md-5 col-md-offset-1">
					Comment<%=select_tag "comments", "",class: "form-control", prompt: "--Select--"%>
				</div>
				<br>
				<br>
				<br>
				<br>
				<div class='col-md-5 col-md-offset-1'>
					 Posts<%=select_tag "post_body", options_for_select(Post.pluck(:id)),class: "form-control", prompt: "-Select post-"%>
				</div>
				<div class="col-md-5 col-md-offset-1">
					Comment's Body<%=select_tag "body", "", class: "form-control", prompt: "--Select--"%>
				</div>
			</div>
		</div>
	</div>
</div>	
<div class="top-margin content-section hidden">
	<div class="col-md-2">
	Username:
	</div>
	<div class="col-md-10 f1">
	na
	</div>
	<div class="col-md-2">
	Email:
	</div>
	<div class="col-md-10 f2">
	na
	</div>
	<div class="col-md-2">
	Password:
	</div>
	<div class="col-md-10 f3">
	na
	</div>
	<div class="col-md-2">
	Confirm Password:
	</div>
	<div class="col-md-10 f4">
	na
	</div>
	<div class="col-md-2">
	Full Text:
	</div>
	<div class="col-md-10 f5">
	na
	</div>
</div>